sudo: required
services:
    - docker
    
before_install:
    - docker build -t brucezwhub/docker-react -f Dockerfile.dev .

script:
    - docker run brucezwhub/docker-react npm run test -- --coverage
    